version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080" # ホストの8080ポートをコンテナの8080ポートにマッピング
    environment:
      - DATABASE_URL=file:./dev.db # 必要な環境変数を設定
    volumes:
      - .:/app
    command: npm start